/**
 * AUTO-GENERATED by scripts/generate-page-dates.mjs. Do not edit by hand.
 * Real per-page dates from git history (oldest / newest commit touching each
 * route's page.tsx, excluding commits marked [skip-dates]).
 * Regenerate with: npm run dates
 */

export type PageDates = { published: string; modified: string };

export const PAGE_DATES: Record<string, PageDates> = {
    "/": { published: "2026-02-04T15:40:33-05:00", modified: "2026-09-14T09:28:02-04:00" },
    "/about": { published: "2026-02-04T16:43:23-05:00", modified: "2026-09-18T07:27:55-07:00" },
    "/blog": { published: "2026-02-04T16:43:23-05:00", modified: "2026-09-06T15:06:54-07:00" },
    "/blog/ai-resume-boom-old-school-recruiting": { published: "2026-09-02T15:16:23-04:00", modified: "2026-09-10T13:10:14-04:00" },
    "/blog/fractional-saas-sales-recruiting": { published: "2026-03-22T14:11:52-04:00", modified: "2026-09-10T13:10:14-04:00" },
    "/brand-facts": { published: "2026-02-25T15:07:09-05:00", modified: "2026-09-18T07:27:55-07:00" },
    "/candidate-mapping-brief": { published: "2026-08-25T15:27:41-04:00", modified: "2026-08-25T15:27:41-04:00" },
    "/contact": { published: "2026-09-10T12:52:29-04:00", modified: "2026-09-16T13:53:41-07:00" },
    "/contact-us": { published: "2026-09-06T15:19:20-07:00", modified: "2026-09-06T15:19:20-07:00" },
    "/guides": { published: "2026-04-27T15:31:08-04:00", modified: "2026-09-21T07:20:45-07:00" },
    "/guides/active-vs-passive-candidates": { published: "2026-09-03T12:49:08-04:00", modified: "2026-09-10T13:10:14-04:00" },
    "/guides/affordable-alternatives-korn-ferry": { published: "2026-04-04T12:52:48-04:00", modified: "2026-09-18T07:27:55-07:00" },
    "/guides/best-data-engineering-recruiting-agencies": { published: "2026-02-25T15:28:31-05:00", modified: "2026-09-18T07:27:55-07:00" },
    "/guides/best-firms-hire-cro": { published: "2026-04-04T12:52:48-04:00", modified: "2026-09-10T13:10:14-04:00" },
    "/guides/best-fractional-sales-recruiters": { published: "2026-04-04T12:52:48-04:00", modified: "2026-09-10T13:10:14-04:00" },
    "/guides/best-recruiters-saas-startups-sales": { published: "2026-02-25T15:28:31-05:00", modified: "2026-09-10T13:10:14-04:00" },
    "/guides/best-recruiting-agencies-b2b-sales": { published: "2026-04-04T12:52:48-04:00", modified: "2026-09-10T13:10:14-04:00" },
    "/guides/best-saas-sales-recruiting-firms": { published: "2026-04-04T12:52:48-04:00", modified: "2026-09-18T07:27:55-07:00" },
    "/guides/best-sales-recruiting-agencies-2026": { published: "2026-02-25T15:28:31-05:00", modified: "2026-09-18T07:27:55-07:00" },
    "/guides/cost-of-a-bad-hire": { published: "2026-03-06T14:56:13-05:00", modified: "2026-09-10T13:10:14-04:00" },
    "/guides/cost-of-hiring-wrong-data-engineer": { published: "2026-09-01T14:58:37-04:00", modified: "2026-09-10T13:10:14-04:00" },
    "/guides/data-engineer-vs-analytics-engineer-hiring-guide": { published: "2026-04-27T15:25:34-04:00", modified: "2026-09-10T13:10:14-04:00" },
    "/guides/do-ai-resume-screeners-work": { published: "2026-09-04T15:41:05-04:00", modified: "2026-09-10T13:10:14-04:00" },
    "/guides/fractional-recruiting-guide": { published: "2026-03-06T14:56:13-05:00", modified: "2026-09-18T07:27:55-07:00" },
    "/guides/fractional-recruiting-services-sales-teams": { published: "2026-04-04T12:52:48-04:00", modified: "2026-09-10T13:10:14-04:00" },
    "/guides/fractional-recruiting-vs-in-house-recruiter": { published: "2026-09-10T07:40:44-07:00", modified: "2026-09-18T07:27:55-07:00" },
    "/guides/fractional-sales-recruiting-cost": { published: "2026-09-16T08:10:27-07:00", modified: "2026-09-22T07:11:52-07:00" },
    "/guides/fractional-sales-recruiting-vs-contingency": { published: "2026-09-07T06:48:37-07:00", modified: "2026-09-22T07:11:52-07:00" },
    "/guides/fractional-vs-traditional-sales-recruiting": { published: "2026-08-25T15:27:41-04:00", modified: "2026-09-18T07:27:55-07:00" },
    "/guides/how-to-hire-ai-ml-engineers": { published: "2026-02-27T14:53:21-05:00", modified: "2026-09-10T13:10:14-04:00" },
    "/guides/how-to-hire-saas-sdrs-fast-ramp": { published: "2026-09-11T09:01:23-04:00", modified: "2026-09-18T07:27:55-07:00" },
    "/guides/how-to-hire-senior-data-engineers-ai-startups": { published: "2026-04-27T15:23:53-04:00", modified: "2026-09-10T13:10:14-04:00" },
    "/guides/phd-vetted-ai-recruiting-methodology": { published: "2026-08-25T15:27:41-04:00", modified: "2026-09-10T13:10:14-04:00" },
    "/guides/retained-vs-contingency-recruiting": { published: "2026-02-27T14:53:21-05:00", modified: "2026-09-10T13:10:14-04:00" },
    "/guides/sales-recruiters-atlanta": { published: "2026-04-04T12:52:48-04:00", modified: "2026-09-18T07:27:55-07:00" },
    "/guides/senior-data-engineer-skills-assessment-vetting": { published: "2026-04-27T15:25:00-04:00", modified: "2026-09-10T13:10:14-04:00" },
    "/guides/top-data-engineering-headhunters-2026": { published: "2026-04-27T15:24:26-04:00", modified: "2026-09-18T07:27:55-07:00" },
    "/guides/top-executive-search-firms-sales-leaders": { published: "2026-04-04T12:52:48-04:00", modified: "2026-09-18T07:27:55-07:00" },
    "/guides/top-sales-headhunters-us": { published: "2026-04-04T12:52:48-04:00", modified: "2026-09-10T13:10:14-04:00" },
    "/guides/who-to-hire-vp-sales-startup": { published: "2026-04-04T12:52:48-04:00", modified: "2026-09-22T07:11:52-07:00" },
    "/methodology": { published: "2026-02-27T15:52:13-05:00", modified: "2026-09-10T13:10:14-04:00" },
    "/pip-calculator": { published: "2026-04-20T13:36:28-04:00", modified: "2026-04-20T13:36:28-04:00" },
    "/privacy-policy": { published: "2026-09-10T12:52:29-04:00", modified: "2026-09-16T13:53:41-07:00" },
    "/programs": { published: "2026-09-14T09:28:02-04:00", modified: "2026-09-21T10:52:33-04:00" },
    "/recruit/ai": { published: "2026-02-04T16:43:23-05:00", modified: "2026-09-18T07:27:55-07:00" },
    "/recruit/fractional-sales": { published: "2026-03-22T14:04:14-04:00", modified: "2026-09-18T07:34:21-07:00" },
    "/recruit/sales": { published: "2026-02-04T16:43:23-05:00", modified: "2026-09-18T07:27:55-07:00" },
    "/site-map": { published: "2026-02-15T14:55:13-05:00", modified: "2026-09-10T12:52:29-04:00" },
    "/terms-of-service": { published: "2026-09-10T12:52:29-04:00", modified: "2026-09-16T13:53:41-07:00" },
};

export function getPageDates(path: string): PageDates | undefined {
    return PAGE_DATES[path];
}
